# Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:


# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def euler002
  sum,a,b=0,1,2
  while b<4000000
    a,b=b,a+b
    sum+=a if a%2==0
  end
  sum
end

puts euler002